#+TITLE: Cil4Sys first meeting

* Tour de table

- Thomas Binetruy
- Philippe Jacquet
- Adrien Ly
- Margaux Rodrigues
- Philippe Gicquel (Cil4Sys)
- Olivier Rouhaud (Softeam)

* Etat de l'art

- Mastere Ponts et Chaussées en /Smart Mobility/
- Contrôle des véhicules
- Synchronisation des feux tricolores
- Vitesse des véhicules
  + Video Ford

1. Centrer l'état de l'art avec des documents sur le contrôle d'infra de feux tricolores
2. Données de dynamique de véhicules
3. Passage de la dynamique au rejet. Pistes:
  + IFPEN
  + Regarder la recherche
  + Contacts de P. Gicquel

Chercher des quartiers au trafic un minimum fluide (donc pas les grosses villes, plutôt s'orienter sur une ville de banlieue parisienne ou province).

Contacter les personnes maintenant car ça peut prendre du temps.

* Work packages
  
** Partie théorique

1. Qu'est ce qu'on peut atteindre si on controle les véhicules et les feux:
2. Ensuite on introduira des perturbations etc
3. Trouver données théoriques sur les dynamiques de trafic.

** Lien entre dynamique automobile et rejets

Avec un peu de chance, IFPEN va nous donner des analyses si on leur donne les données demandées à TomTom. Mais les données TomTom ne sont pas forcément utiles (il faut voir si la granularité est suffisante pout l'IFPEN).

** Études théoriques de recherche d'optimums

*** Contraintes

1. Temps minimum de trajet entre pt A et B
2. Prise en compte des piétons
3. Etc...

** Simulation dans un monde virtuel - impact des perturbations

Ca va permettre d'introduire des éléments de perturbations (piéton qui traverse qu'on avait pas prévu - traverse au rouge etc). Du coup le piéton a fait freiner tout le monde derrière. Faut il changer le comportement du feu en temps réel ?

** Mise en projet d'un potentiel déploiement
   
integrity modeler / papyrus

* Planning

- Trois jalons établis par Telecom avec présentation orale (chaque fin de période).
- Definition des roles
- Points de contacts

CIL4SYS: SCRUM sur periodes de 15 jours (avec un entre-meeting au bout de 7 jours)

P2 start 5 nov - end 30 jan
P3 start 30 jan - end 17 avr
P4 start 17 avr - end 30 juin

** P2
   
- 28-nov-2018 => RDV, 17h @ TP ; reservation de salle
  + Finir de booker les dates de réunions
  + Planning projet + attributions des roles
  + Etat de l'art
- 17-dec-2018 => RDV, 17h30 @ TP ; 21 avenue Victor Hugo 75009
- 22-jan-2018 => RDV, 15h00 @ TP ; reservation de salle
   
** P3
   
** P4

* Partage de documents

- Dropbox fil rouge
